### PR TITLE
Fix #30

### LINKED ISSUE #30: HistoryUndo crashes
running dnfdragora history undo i got the following error:
```
File "/usr/lib64/python3.8/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.8/site-packages/dnfdaemon/server/__init__.py", line 68, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 305, in HistoryUndo
    value = self.history_undo(tid)
  File "/usr/lib/python3.8/site-packages/dnfdaemon/server/__init__.py", line 656, in history_undo
    history = dnf.history.open_history(self.base.history)
AttributeError: module 'dnf.history' has no attribute 'open_history'
```

### PR DESCRIPTION
**Pull request by HollowMan6**
This PR solves #30 when combined with #38

Previously dnfdragora will fail to produce a transaction even after #38 . With this PR now it can undo history installation.

image

image

### CODE REVIEW

**Comment by anaselli** [comment]
Great, I think i have to fix some code in dnfdragora for that though, i'm almost sure i left old synch code there since it didn't work
